- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - block:
        - name: Determine Hosts That Are Up
          wait_for_connection:
            timeout: 1
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"

- hosts: running_hosts
  become: yes
  tasks:
    - name: Change password
      user:
        name: testing
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
